'''

'''
import pandas

def ReadPep(_pepcsv, _target_pep):
    '''

    '''
    pep_df_raw = pandas.read_csv(_pepcsv)
    pep_df_ = pep_df_raw[pep_df_raw['Protein name']\
    .isin([_target_pep])].reset_index(drop = 'TRUE')
    print(pep_df_)
    return pep_df_


def ReadRef(_ref):
    '''

    '''
    ref_df_ = pandas.DataFrame(columns = ['AA', 'FREQ'])

    for i in range(len(_ref)):
        ref_df_.loc[i] = [_ref[i], 0]
    print(ref_df_)
    return ref_df_


def AlignPep(_ref, ref_df_, _pep_df):
    '''
    for peptide in pepdf:
        if peptide in ref:
            ip = ref.index(peptide)

            for ip range:
                ref_df += peptide의갯수

    return ref_df_
    '''



def Plotting(arg):
    '''
    맨해튼플롯
    '''
    pass


def main(arg):
    '''
    인풋아웃풋
    '''
    pass


if __name__ == "__main__":
    _ref = "MGSSHHHHHHSSGLVPRGSHMASMTGGQQMGRGSEFELRRQACGRMSIYQEFVNKYSLSKTLRFELIPQGKTLENIKARGLILDDEKRAKDYKKAKQIIDKYHQFFIEEILSSVCISEDLLQNYSDVYFKLKKSDDDNLQKDFKSAKDTIKKQISEYIKDSEKFKNLFNQNLIDAKKGQESDLILWLKQSKDNGIELFKANSDITDIDEALEIIKSFKGWTTYFKGFHENRKNVYSSNDIPTSIIYRIVDDNLPKFLENKAKYESLKDKAPEAINYEQIKKDLAEELTFDIDYKTSEVNQRVFSLDEVFEIANFNNYLNQSGITKFNTIIGGKFVNGENTKRKGINEYINLYSQQINDKTLKKYKMSVLFKQILSDTESKSFVIDKLEDDSDVVTTMQSFYEQIAAFKTVEEKSIKETLSLLFDDLKAQKLDLSKIYFKNDKSLTDLSQQVFDDYSVIGTAVLEYITQQIAPKNLDNPSKKEQELIAKKTEKAKYLSLETIKLALEEFNKHRDIDKQCRFEEILANFAAIPMIFDEIAQNKDNLAQISIKYQNQGKKDLLQASAEDDVKAIKDLLDQTNNLLHKLKIFHISQSEDKANILDKDEHFYLVFEECYFELANIVPLYNKIRNYITQKPYSDEKFKLNFENSTLANGWDKNKEPDNTAILFIKDDKYYLGVMNKKNNKIFDDKAIKENKGEGYKKIVYKLLPGANKMLPKVFFSAKSIKFYNPSEDILRIRNHSTHTKNGSPQKGYEKFEFNIEDCRKFIDFYKQSISKHPEWKDFGFRFSDTQRYNSIDEFYREVENQGYKLTFENISESYIDSVVNQGKLYLFQIYNKDFSAYSKGRPNLHTLYWKALFDERNLQDVVYKLNGEAELFYRKQSIPKKITHPAKEAIANKNKDNPKKESVFEYDLIKDKRFTEDKFFFHCPITINFKSSGANKFNDEINLLLKEKANDVHILSIDRGERHLAYYTLVDGKGNIIKQDTFNIIGNDRMKTNYHDKLAAIEKDRDSARKDWKKINNIKEMKEGYLSQVVHEIAKLVIEYNAIVVFEDLNFGFKRGRFKVEKQVYQKLEKMLIEKLNYLVFKDNEFDKTGGVLRAYQLTAPFETFKKMGKQTGIIYYVPAGFTSKICPVTGFVNQLYPKYESVSKSQEFFSKFDKICYNLDKGYFEFSFDYKNFGDKAAKGKWTIASFGSRLINFRNSDKNHNWDTREVYPTKELEKLLKDYSIEYGHGECIKAAICGESDKKFFAKLTSVLNTILQMRNSKTGTELDYLISPVADVNGNFFDSRQAPKNMPQDADANGAYHIGLKGLMLLGRIKNNQEGKKLNLVIKNEEYFEFVQNRNNQAAALEKRPAATKKAGQAKKKKSTPPPPPLRSGC"
    _pep_df = ReadPep('./KHS_1.csv', 'FN_Add_1to3')
    ref_df_ = ReadRef(_ref)
